name: Update Organization Profile README

on:
  push:
    branches: [ 'main' ]
    
jobs:
  update-org-profile:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clone the .github Repository
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Clone the .github repository
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/twilightchat/.github.git profile

      - name: Copy README to Organization Profile
        run: |
          # Copy the README to the .github profile directory
          mkdir -p profile/profile
          cp README.md profile/profile/README.md

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          cd profile
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/README.md
          # Commit only if there are changes
          git commit -m "Update organization profile README from repo README"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/twilightchat/.github.git
